import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createJiti } from 'jiti';
const jiti = createJiti(import.meta.url);
const { addGenericLearningSource, readLearningStore, listConfirmedGenericSources, snapshotConsolidationBatch, saveConsolidationProposals, mutateLearningRule, readActiveGenericLessons } = await jiti.import('./grounding-learning-store.ts');
const { consolidateGenericLearning, buildConsolidationRequest } = await jiti.import('./grounding-learning-consolidator.ts');
const { appendGroundingLesson, selectGroundingLessons } = await jiti.import('./grounding-learning.ts');
const advice = 'Preserve uncertain interpretations until visible structural evidence distinguishes them.';
const procedure = { category:'uncertainty', applicability:'Ambiguous visual interpretations', error:'Repeated views can be mistaken for independent evidence.', method:'Retain competing interpretations and inspect only a specific unresolved structural question.', check:'Keep unresolved uncertainty explicit without inventing evidence.' };
async function fixture(t) { const root = await mkdtemp(join(tmpdir(),'generic-learning-')); t.after(()=>rm(root,{recursive:true,force:true})); const legacyPath=join(root,'v2.jsonl'); return {legacyPath,filePath:`${legacyPath}.consolidation-v3.json`}; }
const options={provider:'fake',modelId:'fake',maxOutputTokens:1000,timeoutMs:1000};
async function propose(paths) { await addGenericLearningSource({text:advice,sampleIndependent:true},paths); const batch=await snapshotConsolidationBatch(paths); const input={sourceIds:batch.sources.map(s=>s.id),operation:'normalize',procedure,note:'Organizes a general procedure while preserving uncertainty.'}; const proposals=await consolidateGenericLearning(batch,options,async()=>JSON.stringify([input])); return saveConsolidationProposals(batch,proposals,paths); }
test('generic text confirmation and exact concurrent dedup happen before persistence',async t=>{const paths=await fixture(t); await assert.rejects(addGenericLearningSource({text:advice,sampleIndependent:false},paths)); for(const text of ['query: a private sample','sample_017','bbox: [0, 0, 1, 1]','answer: a secret answer','/images/private.png']) await assert.rejects(addGenericLearningSource({text,sampleIndependent:true},paths)); await assert.rejects(addGenericLearningSource({text:advice,sampleIndependent:true,query:'secret'},paths)); await Promise.all(Array.from({length:5},()=>addGenericLearningSource({text:advice,sampleIndependent:true},paths))); const store=await readLearningStore(paths); assert.equal(store.sources.length,1); assert.equal(store.revision,1); });
test('v2 is read-only projected and legacy sample-bearing rows are excluded',async t=>{const paths=await fixture(t); await writeFile(paths.legacyPath,JSON.stringify({version:1,query:'RAW_SAMPLE_SENTINEL'})+'\n'); await appendGroundingLesson({...procedure,sampleIndependent:true},paths.legacyPath); const before=await readFile(paths.legacyPath,'utf8'); const sources=await listConfirmedGenericSources(paths); assert.equal(sources.length,1); assert.equal(sources[0].origin,'v2'); assert.doesNotMatch(JSON.stringify(sources),/RAW_SAMPLE_SENTINEL/); assert.equal(await readFile(paths.legacyPath,'utf8'),before); });
test('AI receives only generic sources and pending proposals never enter active retrieval',async t=>{const paths=await fixture(t); const store=await propose(paths); assert.equal(store.proposals[0].status,'pending'); assert.deepEqual(await readActiveGenericLessons(paths),[]); assert.deepEqual(await selectGroundingLessons({filePath:paths.legacyPath}),[]); const batch=await snapshotConsolidationBatch(paths); const request=buildConsolidationRequest(batch); assert.deepEqual(Object.keys(JSON.parse(request.text).sources[0]).sort(),['id','text']); assert.equal((await snapshotConsolidationBatch({...paths,excludeSourceIds:batch.sources.map(s=>s.id)})).sources.length,0); assert.equal((await snapshotConsolidationBatch({...paths,maxChars:10})).sources.length,0); });
test('proposal validation rejects unknown fields, source references, payloads and tool-shaped output',async t=>{const paths=await fixture(t); await addGenericLearningSource({text:advice,sampleIndependent:true},paths); const batch=await snapshotConsolidationBatch(paths); const input={sourceIds:[batch.sources[0].id],operation:'normalize',procedure,note:'A general procedural normalization.'}; for(const output of ['not json',JSON.stringify([{...input,query:'secret'}]),JSON.stringify([{...input,sourceIds:['a'.repeat(64)]}]),JSON.stringify([{...input,procedure:{...procedure,method:'answer: hidden specific target'}}]),JSON.stringify([{...input,procedure:{...procedure,sampleIndependent:true}}])]) await assert.rejects(consolidateGenericLearning(batch,options,async()=>output)); await assert.rejects(consolidateGenericLearning({...batch,sources:[{...batch.sources[0],query:'private'}]},options,async()=>{assert.fail('must not call');})); });
test('human activation, stale mutation guard, disable, restore and revision rollback',async t=>{const paths=await fixture(t); let store=await propose(paths); await assert.rejects(mutateLearningRule({type:'activate',proposalId:store.proposals[0].id,sampleIndependent:false},store.revision,paths)); store=await mutateLearningRule({type:'activate',proposalId:store.proposals[0].id,sampleIndependent:true},store.revision,paths); assert.equal((await selectGroundingLessons({filePath:paths.legacyPath})).length,1); const ruleId=store.rules[0].id; await assert.rejects(mutateLearningRule({type:'set_enabled',ruleId,enabled:false},0,paths),/revision conflict/); store=await mutateLearningRule({type:'set_enabled',ruleId,enabled:false},store.revision,paths); assert.equal((await readActiveGenericLessons(paths)).length,0); store=await mutateLearningRule({type:'set_enabled',ruleId,enabled:true},store.revision,paths); const batch=await snapshotConsolidationBatch(paths); store=await saveConsolidationProposals(batch,[{sourceIds:batch.sources.map(s=>s.id),operation:'normalize',procedure:{...procedure,check:'Recheck unresolved interpretations and retain uncertainty.'},note:'A clarified general check.'}],paths); const pending=store.proposals.find(p=>p.status==='pending'); store=await mutateLearningRule({type:'activate',proposalId:pending.id,sampleIndependent:true,ruleId},store.revision,paths); assert.equal(store.rules[0].revisions.length,2); store=await mutateLearningRule({type:'rollback',ruleId,revision:1},store.revision,paths); assert.equal(store.rules[0].currentRevision,1); assert.equal(store.rules[0].revisions.length,2); });
test('dedup proposals and unreadable optional store leave legacy retrieval usable',async t=>{const paths=await fixture(t); await propose(paths); let store=await propose(paths); assert.equal(store.proposals.length,1); await appendGroundingLesson({...procedure,sampleIndependent:true},paths.legacyPath); await writeFile(paths.filePath,'{ corrupt'); assert.equal((await selectGroundingLessons({filePath:paths.legacyPath})).length,1); });
test('source text is preserved verbatim and stored proposal refs must resolve',async t=>{const paths=await fixture(t); const text=`  ${advice}\r\n`; let store=await addGenericLearningSource({text,sampleIndependent:true},paths); assert.equal(store.sources[0].text,text); assert.equal((await readLearningStore(paths)).sources[0].text,text); const batch=await snapshotConsolidationBatch(paths); assert.equal(JSON.parse(buildConsolidationRequest(batch).text).sources[0].text,text); store=await saveConsolidationProposals(batch,[{sourceIds:[batch.sources[0].id],operation:'normalize',procedure,note:'General advice is organized for human review.'}],paths); store.sources=[]; await writeFile(paths.filePath,JSON.stringify(store)); await assert.rejects(readLearningStore(paths),/invalid/); });
test('proposal keeps only generic v2 source snapshot and never rewrites legacy data',async t=>{const paths=await fixture(t); await appendGroundingLesson({...procedure,sampleIndependent:true},paths.legacyPath); const original=await readFile(paths.legacyPath,'utf8'); const batch=await snapshotConsolidationBatch(paths); const store=await saveConsolidationProposals(batch,[{sourceIds:[batch.sources[0].id],operation:'normalize',procedure,note:'Preserve the general procedure for human review.'}],paths); assert.equal(store.sources[0].origin,'v2'); assert.equal(store.sources[0].text,batch.sources[0].text); assert.equal(await readFile(paths.legacyPath,'utf8'),original); assert.equal((await readLearningStore(paths)).proposals.length,1); });
test('cancelled proposal waiting for store lock cannot commit',async t=>{const paths=await fixture(t); await addGenericLearningSource({text:advice,sampleIndependent:true},paths); const batch=await snapshotConsolidationBatch(paths); const {default:lockfile}=await import('proper-lockfile'); const release=await lockfile.lock(paths.filePath,{realpath:false}); let canCommit=true; let guardCalls=0; const original=await readFile(paths.filePath,'utf8'); const pending=saveConsolidationProposals(batch,[{sourceIds:[batch.sources[0].id],operation:'normalize',procedure,note:'A general procedure awaiting review.'}],paths,()=>{guardCalls++;return canCommit;}); const failure=assert.rejects(pending,/cancelled/); await new Promise(resolve=>setTimeout(resolve,40)); assert.equal(guardCalls,0,'guard must run after lock acquisition'); canCommit=false; await release(); await failure; assert.ok(guardCalls>0); assert.equal(await readFile(paths.filePath,'utf8'),original); });
test('oversized source does not starve later sources that fit the input budget',async t=>{const paths=await fixture(t); await addGenericLearningSource({text:'Keep uncertain interpretations separate. '.repeat(50),sampleIndependent:true},paths); await addGenericLearningSource({text:advice,sampleIndependent:true},paths); const batch=await snapshotConsolidationBatch({...paths,maxChars:1000}); assert.equal(batch.sources.length,1); assert.equal(batch.sources[0].text,advice); });
test('injected provider initialization failure is sanitized for direct callers',async t=>{const paths=await fixture(t); await addGenericLearningSource({text:advice,sampleIndependent:true},paths); const batch=await snapshotConsolidationBatch(paths); await assert.rejects(consolidateGenericLearning(batch,options,async()=>{throw new Error('PRIVATE_PROVIDER_PAYLOAD sk-secret');}),error=>{assert.doesNotMatch(error.message,/PRIVATE_PROVIDER_PAYLOAD|sk-secret/);assert.match(error.message,/provider request failed/);return true;}); });
